### ISSUE TITLE
Does not use Bandersnatch properly

### ISSUE THREAD

**Issue by gausie** [linknoid/MafiaScripts#3]
https://github.com/linknoid/MafiaScripts/blob/e45fc0cbd5cd0905f619c605289e40d3a18b8659/LinknoidBarf.ash#L5232-L5240

Assuming this is a typo

**Comment by linknoid** [comment]
Yeah, that's a copy/paste error.  I have some other changes I'm in the middle of, so the fix will be committed with them.  But they're the kind of changes that take multiple days to test (neverending party quests), so it might be a bit before I push that change out.
